---

- name: Restart Elasticsearch container
  docker_container:
    name: "{{ elasticsearch_docker_container_name }}"
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ elasticsearch_version }}"
    state: started
    network_mode: host
    restart_policy: "unless-stopped"
    ports:
      - "{{ elasticsearch_http_port }}:9200"
      - "{{ elasticsearch_transport_port }}:9300"
    volumes:
      - "elasticsearch_data_dir:/usr/share/elasticsearch/data:rw"
    env: "{{ elasticsearch_options | combine(elasticsearch_additional_options) }}"
