---
- name: Adjust system settings
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: Start Elasticsearch container
  docker_container:
    name: "{{ elasticsearch_docker_container_name }}"
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ elasticsearch_version }}"
    state: started
