---
- name: Install python-pip
  package:
    name: python-pip
    state: present

- name: Install docker-py
  pip:
    name: docker-py

- name: Set Elasticsearch options
  set_fact:
    elasticsearch_options:
      ES_JAVA_OPTS: "-Xms{{ elasticsearch_memory }} -Xmx{{ elasticsearch_memory }}"
      cluster.name: "{{ elasticsearch_cluster_name }}"
      node.name: "{{ inventory_hostname }}-{{ elasticsearch_instance_name }}"
      bootstrap.memory_lock: "false"
      discovery.zen.ping.unicast.hosts: "{% for item in ansible_play_hosts %} {{ hostvars[item]['ansible_' + elasticsearch_interface]['ipv4']['address'] }}{% if not loop.last %}, {% endif %}{% endfor %}"
      discovery.zen.minimum_master_nodes: "1"
      node.master: "{% if elasticsearch_master_node %}true{% else %}false{% endif %}"
      node.data: "{% if elasticsearch_data_node %}true{% else %}false{% endif %}"
      node.ingest: "{% if elasticsearch_ingest_node %}true{% else %}false{% endif %}"

- name: Download Elasticsearch container
  docker_container:
    name: "{{ elasticsearch_docker_container_name }}"
    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ elasticsearch_version }}"
    state: started
    network_mode: host
    restart_policy: "unless-stopped"
    ports:
      - "{{ elasticsearch_http_port }}:9200"
      - "{{ elasticsearch_transport_port }}:9300"
    volumes:
      - "elasticsearch_data_dir:/usr/share/elasticsearch/data:rw"
    env: "{{ elasticsearch_options | combine(elasticsearch_additional_options) }}"
