---
# TODO add support for installing plugins from local file

- name: Install elasticsearch plugins
  command: "docker exec {{ elasticsearch_docker_container_name }} \
    /usr/share/elasticsearch/bin/elasticsearch-plugin install \
    {{ item.plugin }}{% if item.version is defined and item.version != '' %}/{{ item.version }}{% endif %} \
    {% if http_proxy is defined %} -DproxyHost={{ http_proxy.split('/')[-1].split(':')[0] }} \
    -DproxyPort={{ http_proxy.split('/')[-1].split(':')[1] }}{% endif %} --silent"
  register: plugin_installed
  failed_when: "'ERROR' in plugin_installed.stdout"
  changed_when: plugin_installed.rc == 0
  with_items: "{{ elasticsearch_plugins }}"
  notify: Restart container
